site_name: Documentation
site_url: 'https://waterlinked.github.io'
theme:
    name: material
    theme_dir: docstheme/material
    logo: img/waterlinked_logo_new.png
    favicon: 'img/favicon_water_linked.ico'
    palette:
        primary: blue-grey
        accent: blue
extra:
    social:
      - type: github
        link: https://github.com/waterlinked/
      - type: facebook
        link: https://www.facebook.com/waterlinked/
      - type: youtube
        link: https://www.youtube.com/channel/UCZFmOcapjyWgEnS_l6JgxQg/

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta


extra_css:
    - css/extra.css

pages:
    - Explorer Kit:
        - Introduction: explorer-kit/introduction.md
        - Warnings: explorer-kit/warnings.md
        - Power supply: explorer-kit/power-supply.md
        - Hardware: explorer-kit/hardware.md
        - GUI:
            - Position: explorer-kit/gui/position.md
            - Receivers: explorer-kit/gui/receivers.md
            - Settings: explorer-kit/gui/settings.md
            - Diagnostic: explorer-kit/gui/diagnostic.md
            - Upgrader: explorer-kit/gui/upgrader.md
            - API: explorer-kit/gui/api.md

    # - Developer Bundle:
    #     - Introduction: developer-bundle/introduction.md
    #     - Warnings: developer-bundle/warnings.md
    #     - General: developer-bundle/general.md
    #     - Hardware Setup: developer-bundle/hardware-setup.md
    #     - Software: developer-bundle/software.md
    #     - Spesifications: developer-bundle/spesifications.md
    #     - Diagnostics: developer-bundle/diagnostics.md

    - Locators:
        - Introduction: locators/introduction.md
        - Locator-A1: locators/locator-a1.md
        - Locator-D1: locators/locator-d1.md
        - Locator-S1: locators/locator-s1.md
        - Locator-U1: locators/locator-u1.md

    - Receiver-D1: receiver-d1.md
    - Master-D1: master-d1.md
    - Quickstart: quickstart.md
    - Tutorials: tutorials.md
    - Helpful Links: helpful-links.md

copyright: Â© Water Linked 2018